### ISSUE TITLE
Error resolving nuummite (~> 0.1)

### ISSUE THREAD

**Issue by sethkrasnianski** [CodeSteak/Nuummite#2]
I'll preface this with the fact that I'm very new to Crystal, bu when I update my `shard.yml` with:

``` yaml
dependencies:
  nuummite:
    github: codesteak/nuummite
    version: ~> 0.1.0
```

... I get `Error resolving nuummite (~> 0.1)`

Any idea if this is a shards-specific issue? Or does this have something to do with the Nuummite `shard.yml`?
